### ISSUE TITLE
Cannot retrieve documents through proxy

### ISSUE THREAD

**Issue by lbrossault** [aptnotes/tools#4]
Hello,

I cannot retrieve any documents through a proxy. I have still the following message:
**./APTnotes_sync_download.py**
[!] Download failure for Kaspersky_OlympicDestroyerisstillalive(06-19-2018) HTTPSConnectionPool(host='app.box.com', port=443): Max retries exceeded with url: /s/v49iu7e3x1tawdlpcj7f0wp76js4tl3i (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',)))

Any idea ?

Regards,

**Comment by lbrossault** [comment]
Solution found.

**Comment by lhccst** [comment]
what is the solution
